version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/nathany/get-programming-with-go
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            go get -u github.com/golang/lint/golint
            test -z "$(golint ./... | tee /dev/stderr)"
            go vet ./...
      - run:
          name: Test
          command: go test -race ./...
