application: twitter-1012
version: main
runtime: go
api_version: go1

handlers:
- url: /public
  static_dir: public
- url: /login
  login: required
  script: _go_app
- url: /.*
  script: _go_app

inbound_services:
- mail
