application: photo-blog-1008
version: 1
runtime: go
api_version: go1

handlers:
- url: /admin
  secure: always
  login: admin
  script: _go_app
- url: /(style.css|favicon.ico)
  secure: optional
  script: _go_app
- url: /.*
  secure: never
  script: _go_app
